services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: audioapp
    ports:
      - "7001:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/audioapp
      JWT_SECRET: supersecret
    ports:
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/src/uploads

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  db_data:
